language: node_js
node_js:
- node
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: radio.web@media.ucla.edu
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: uclaradio/eslint-config-uclaradio
