language: node_js
node_js:
- node
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: radio.web@media.ucla.edu
  api_key:
    secure: gHSbtBkgSe1HOfBlfhCv2yTGMMB6Y9NU/+1Jy205iRlAIjggPrMBqcOO3Ew5sJQUEK8JIKDmReqJa+x69py4O6AsihB8Q18Bn4NzZeEaOOjHBKZCmn9BF7Ja3Kfp8mMcbfURURd8rCAvvRIITD2Pf1Vo6L0Wk3hgAM5OSL9xrO9aWp3fxPMa62Gt3+oLRqK06iil/E0xsZiMg1loQ9pldHcl2Hjl41cKhWwWnmrDC7l80vbn5uXf8IrSxZz8JYMOOUaLchcIRTJHJDSODer4GmyGIShkls7HLMp13JiuDt8/Km5R9aLnEjN5RpF7WEVJ1N26j68rT8LlXzT8wvYL97JOfZJ323B+qvtvLXuv81nya8/1sVVrzF/xRXMFHQEuI1JZgY1QJKBJJFhXLpUWHXOa11DDrMfbUHG+S8jBzA0Qk1OvIYP12zBFP6Zof/Gvod4paekmkLEg0PQle1aLKqofrqjfR3+ad0AaGzCgweqjaZGzGxVhnLynfxXBthNV8AGoRc+LAaO1WpYabVjCroc4b1+5DJ+kaIUmkPPc/3CBmOVhYiZOVJ5JLFPWP8wxt2oz4fOjs/351IVSKiosaVFGoa+/j+HvOsA7yWfNo9snOT1D7OnzFUHvh/AIkpgbXjdNexX+fEMfXOVaLucPI4iEvlADbX/0Exh5M/JkKYg=
  on:
    tags: true
    repo: uclaradio/eslint-config-uclaradio
env:
  global:
    secure: Xb9gTodSI0ApoYaz4P7BodXZM8gN66Ri68Hqe1gZBhyyoNiKFtqC8wTeH6jAxHbAvQ24+CsGZ0nXgOiIAO1OC/WJnbCeHAgcibw6MZN6RZEc8YvBaPWVd/6uVRhrpihQtVxMAYgjMp4z/vcKcSGUKDjFca7vB3z7U2RlxsvrCAMfL7iVtz8s/sx5Gu0drGliBs3sIFUh7ODhPl1FY+yzc881YG/T6dooBb2S03eOiRHdmFoDVvdMYHUNGFpEHMLAbtOA9wc0CdiC55If30B9p7vffCIlFYFNPRyvJiIsWex2FIJcBdwXzJNBZxWCpbNBp9MopHbqhHnc+0cEgEbfh+RNgrx0nYAlIMdKlyxDehmf4QnXHQE3yYHVCUxNd/jN6MBDzCYFb7Bnho7zwhdrvEZKoFXqirdkrC5yW3lN4k5ge/WO/glOxHeWNCIgv+56gmNkA1H8drbYEx4ETwjY+QZOkAZEw/n08+jiAmub/ueX6d1jIBs4AxOCz5mY6S6yaSNv21iEayViQaHUh9KiOGsV4En46NcWGCZ1tq7YeCBHe4glHqLMu/FIJpsL2dgjq2dNsORs5PvO+AP6PSdDulWJbjZCotiEK+rfqtyxgnmItbssH6JiVBw7AEz10e61u84HuqkFcYHoVkvP1sGi8bXch4GmWpzDn0Yse45ryIg=
